name: util/initwithconfigmap
parameters:
  - name: configmap
    type: string
  - name: scriptname
    type: string
---
- type: add
  path:
  - spec
  - template
  - spec
  - initContainers
  value:
    - name: script
      image: flokkr/base:36
      args:
      - /opt/script/{{.scriptname}}
      volumeMounts:
      - name: script
        mountPath: /opt/script/{{.scriptname}}
        subPath: {{.scriptname}}
- type: add
  path:
  - spec
  - template
  - spec
  - volumes
  value:
      - name: script
        configMap:
           name: {{.configmap}}
           defaultMode: 0755
