apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-ingress-admin
subjects:
    - kind: ServiceAccount
      name: traefik-ingress
      namespace: kube-system
roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
